version: '3'
services:
  planner:
    build:
      context: .
      dockerfile: ./planner
    depends_on:
      - worker
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: ./worker
    networks:
      - mynetwork
    deploy:
      replicas: 10

networks:
  mynetwork:
    driver: bridge